### ISSUE TITLE
Hide mirrored setups

### ISSUE THREAD

**Issue by eight04** [knewjade/tsd-opener#2]
Can we have an option that hides mirrored setups? I think mirrored setups can be considered as the same build.

BTW, how do you generate all these data?

**Comment by knewjade** [comment]
@eight04 OK 👌 I will do later (It may take some time because I have other works)

[solution-finder](https://github.com/knewjade/solution-finder) can find all t-spins. After that, the output is imaged by solution-finder (`util fig` command).

**Article summarizing Opening T-Spins in Japanese**: https://knewjade.github.io/tetris-knowledge/opening_tspins.html
**Internal script files**: https://github.com/knewjade/sfinder-experimental/tree/max35/src/main/kotlin/tsd_opener

**Comment by knewjade** [comment]
I did it. If `Mirror` is on, both symmetric setups are included. If `Mirror` is off, includes only one of the symmetric setups.

<img width="864" alt="スクリーンショット 2020-01-19 22 27 43" src="https://user-images.githubusercontent.com/27051545/72681879-2f273880-3b0b-11ea-9f97-677d9163dc3c.png">

**Comment by eight04** [comment]
:+1:
Another question: it seems that the current solution-finder doesn't support minos order:
http://sfinder.s3-website-ap-northeast-1.amazonaws.com/contents/spin/main.html#id5

How did you generate all solutions for each permutation?

**Comment by knewjade** [comment]
>  current solution-finder doesn't support minos order

oh. that's right, sorry. so solution-finder alone cannot generate all solutions. 
The data on this site calculated 272 solutions from combinations of 7 minos by solution-finder, and then categorized by permutation by specialized scripts (https://github.com/knewjade/sfinder-experimental/blob/max35/src/main/kotlin/tsd_opener/to_json.kt).
